# Generated by Django 2.1.5 on 2019-02-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_auto_20190207_0944'),
    ]

    operations = [
        migrations.RenameField(
            model_name='branch',
            old_name='longtitude',
            new_name='longitude',
        ),
    ]
